### ISSUE TITLE
Reduce MAX_NAME_LENGTH by 1

### ISSUE THREAD

**Issue by MarkDavidson** [TAXIIProject/django-taxii-services#37]
https://github.com/TAXIIProject/django-taxii-services/blob/master/taxii_services/models.py#L23

This constant should be specified as `255` so that the schema is valid for MySQL. I'm guessing this will also help for other database systems.

**Comment by itchycube** [comment]
Worked perfectly - thanks Mark.

**Comment by MarkDavidson** [comment]
@itchycube, did you change this locally? Either way, it's in the master branch now!

**Comment by itchycube** [comment]
I did just change it locally to test.  Glad's its in there!

Thanks Mark.
