### ISSUE TITLE
Discovery response & Collection Information Response needs a fully qualified URL in <Address> element

### ISSUE THREAD

**Issue by ScottyAU** [TAXIIProject/django-taxii-services#40]
Currently a discovery response returns just a path without the hostname in the \<Address\> element.  

After discussing on the TAXII mailing list [1], consensus is that the \<Address\> element should be a fully qualified URL.

@MarkDavidson suggested there could be a django-solo config instance in django-taxii-services which holds a server hostname to use (if specified), or if the value is not specified, the code could attempt to auto-detect the correct value.

Sounds fair to me.  

1. http://making-security-measurable.1364806.n2.nabble.com/TAXII-Discovery-Response-Question-SEC-UNCLASSIFIED-td7586075.html

**Comment by MarkDavidson** [comment]
@ScottyAU 

Thank you for opening this issue. This is a bit mucky, but there is some work on using Solo in the logging branch. It has a `get_url_base()` function [1] that could be leveraged for your purposes. Probably a little more logic would have to be added (in order to be prepared for the site not being configured yet, or having a bad configuration), but this may be a decent starting point.

If that code is wonky and doesn't work right, please don't hesitate to break from it.

Thank you.
-Mark

[1] https://github.com/TAXIIProject/django-taxii-services/blob/logging/taxii_services/models.py#L1753

**Comment by ScottyAU** [comment]
Thanks @MarkDavidson   

I started looking on the weekend.  What I did note was that after making a change to fix the discovery response to return a fully qualifed value for the /<Address/> element - I then got the same path only type element in a Collection Information Response - so I've added fixing that to this issue too.

Both of these are blocking intergration with Soltra Edge.

**Comment by ScottyAU** [comment]
Thanks so much for this @jasenj1 

This only addresses the discovery response though - not the collection management response...

Would you prefer a seperate issue for that?

Cheers.

**Comment by jasenj1** [comment]
The fix should be for all service addresses. I'll have to look into where the CIR is getting the URL. Sorry, I thought the change would fix all the address problems.

- Jasen.

**Comment by jasenj1** [comment]
I believe I have it fixed now. Found some other places where .path was used and needed to be changed to using the full address.

- Jasen.

**Comment by ScottyAU** [comment]
Thanks @jasenj1 

I updated django-taxii services on the host, but am now getting a 500 back form Yeti when trying to do a discovery response:

&lt;pre class="exception_value"&gt;(u&amp;#39;Error importing handler: taxii_services.DiscoveryRequestHandler&amp;#39;, &amp;lt;type &amp;#39;exceptions.AttributeError&amp;#39;&amp;gt;, AttributeError(&amp;quot;&amp;#39;module&amp;#39; object has no attribute &amp;#39;DiscoveryRequestHandler&amp;#39;&amp;quot;,))&lt;/pre&gt;

And similar when i try a collection management response:

<h1>AttributeError at /services/collection-management/</h1>
  <pre class="exception_value">(u&#39;Error importing handler: taxii_services.CollectionInformationRequestHandler&#39;, &lt;type &#39;exceptions.AttributeError&#39;&gt;, AttributeError(&quot;&#39;module&#39; object has no attribute &#39;CollectionInformationRequestHandler&#39;&quot;,))</pre>

I'll try and do a bit of digging today.  The only change was a pull on django-taxii-services.

Cheers.

**Comment by jasenj1** [comment]
Looks like you don't have the new version of YETI. We changed some of the object names.

"taxii_services.XXX" has been removed. It's now "taxii_services.message_handlers.XXX". If you grab the latest version of YETI the database has been updated with the new names. It has to do with managing imports.

Sorry about that.

- Jasen.

**Comment by ScottyAU** [comment]
Ah - thanks @jasenj1 

I had the latest Yeti - just needed a '''python manage.py syncdb'''

Cheers for both of these fixes!

Scotty
